// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: mapreduce.proto

package MapReduce

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MapReduceServiceClient is the client API for MapReduceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapReduceServiceClient interface {
	AskForTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	SendMapResult(ctx context.Context, in *MapResultMessage, opts ...grpc.CallOption) (*Bool, error)
	SendReduceResult(ctx context.Context, in *ReduceResultMessage, opts ...grpc.CallOption) (*Bool, error)
}

type mapReduceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapReduceServiceClient(cc grpc.ClientConnInterface) MapReduceServiceClient {
	return &mapReduceServiceClient{cc}
}

func (c *mapReduceServiceClient) AskForTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/MapReduce.MapReduceService/AskForTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceServiceClient) SendMapResult(ctx context.Context, in *MapResultMessage, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/MapReduce.MapReduceService/SendMapResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceServiceClient) SendReduceResult(ctx context.Context, in *ReduceResultMessage, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/MapReduce.MapReduceService/SendReduceResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapReduceServiceServer is the server API for MapReduceService service.
// All implementations must embed UnimplementedMapReduceServiceServer
// for forward compatibility
type MapReduceServiceServer interface {
	AskForTask(context.Context, *TaskRequest) (*TaskResponse, error)
	SendMapResult(context.Context, *MapResultMessage) (*Bool, error)
	SendReduceResult(context.Context, *ReduceResultMessage) (*Bool, error)
	mustEmbedUnimplementedMapReduceServiceServer()
}

// UnimplementedMapReduceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMapReduceServiceServer struct {
}

func (UnimplementedMapReduceServiceServer) AskForTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskForTask not implemented")
}
func (UnimplementedMapReduceServiceServer) SendMapResult(context.Context, *MapResultMessage) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMapResult not implemented")
}
func (UnimplementedMapReduceServiceServer) SendReduceResult(context.Context, *ReduceResultMessage) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReduceResult not implemented")
}
func (UnimplementedMapReduceServiceServer) mustEmbedUnimplementedMapReduceServiceServer() {}

// UnsafeMapReduceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapReduceServiceServer will
// result in compilation errors.
type UnsafeMapReduceServiceServer interface {
	mustEmbedUnimplementedMapReduceServiceServer()
}

func RegisterMapReduceServiceServer(s grpc.ServiceRegistrar, srv MapReduceServiceServer) {
	s.RegisterService(&MapReduceService_ServiceDesc, srv)
}

func _MapReduceService_AskForTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServiceServer).AskForTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MapReduce.MapReduceService/AskForTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServiceServer).AskForTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduceService_SendMapResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapResultMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServiceServer).SendMapResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MapReduce.MapReduceService/SendMapResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServiceServer).SendMapResult(ctx, req.(*MapResultMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduceService_SendReduceResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceResultMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServiceServer).SendReduceResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MapReduce.MapReduceService/SendReduceResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServiceServer).SendReduceResult(ctx, req.(*ReduceResultMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// MapReduceService_ServiceDesc is the grpc.ServiceDesc for MapReduceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapReduceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MapReduce.MapReduceService",
	HandlerType: (*MapReduceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskForTask",
			Handler:    _MapReduceService_AskForTask_Handler,
		},
		{
			MethodName: "SendMapResult",
			Handler:    _MapReduceService_SendMapResult_Handler,
		},
		{
			MethodName: "SendReduceResult",
			Handler:    _MapReduceService_SendReduceResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mapreduce.proto",
}
